/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DoctorDTO } from './doctorDTO';
import type { PatientDTO } from './patientDTO';

export interface AppointmentDTO {
    appointmentDate?: string;
    appointmentId?: number;
    appointmentTime?: string;
    /** @nullable */
    createdAt?: string | null;
    doctor?: DoctorDTO;
    doctorId?: number;
    patient?: PatientDTO;
    patientId?: number;
    /** @nullable */
    status?: string | null;
}
