/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { AppointmentDTO } from './appointmentDTO';

export interface AppointmentDTOPaginated {
    /** @nullable */
    data?: AppointmentDTO[] | null;
    nextPage?: number;
    totalItems?: number;
}
