/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Appointment } from './appointment';

export interface AppointmentPaginated {
    /** @nullable */
    data?: Appointment[] | null;
    totalItems?: number;
}
