/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export type AssignDoctorParams = {
    ticketId?: string;
    doctorId?: number;
};
