/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { AppointmentByDepartmentDTO } from './appointmentByDepartmentDTO';
import type { WeeklyAppointmentDTO } from './weeklyAppointmentDTO';
import type { WeeklyRevenueDTO } from './weeklyRevenueDTO';

export interface DashboardDTO {
    /** @nullable */
    appointmentsByDepartment?: AppointmentByDepartmentDTO[] | null;
    /** @nullable */
    weeklyAppointments?: WeeklyAppointmentDTO[] | null;
    /** @nullable */
    weeklyRevenue?: WeeklyRevenueDTO[] | null;
}
