/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DepartmentDTO } from './departmentDTO';

export interface DepartmentDTOPaginated {
    /** @nullable */
    data?: DepartmentDTO[] | null;
    totalItems?: number;
}
