/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Book API
 * OpenAPI spec version: v1
 */
import type { Doctor } from './doctor';

export interface Department {
    departmentId?: number;
    /**
     * @minLength 0
     * @maxLength 100
     * @nullable
     */
    departmentName?: string | null;
    /**
     * @minLength 0
     * @maxLength 255
     * @nullable
     */
    description?: string | null;
    /** @nullable */
    doctors?: Doctor[] | null;
}
