/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Diagnosis } from './diagnosis';

export interface DiagnosisPaginated {
    /** @nullable */
    data?: Diagnosis[] | null;
    totalItems?: number;
}
