/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface DoctorScheduleCreateDTO {
    dayOfWeek?: number;
    doctorId?: number;
    endTime?: string;
    scheduleId?: number;
    startTime?: string;
}
