/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Doctor } from './doctor';

export interface DoctorSchedule {
    dayOfWeek?: number;
    doctor?: Doctor;
    doctorId?: number;
    endTime?: string;
    scheduleId?: number;
    startTime?: string;
}
