/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Doctor } from './doctor';

export interface DoctorPaginated {
    /** @nullable */
    data?: Doctor[] | null;
    totalItems?: number;
}
