/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DoctorSchedule } from './doctorSchedule';

export interface DoctorSchedulePaginated {
    /** @nullable */
    data?: DoctorSchedule[] | null;
    totalItems?: number;
}
