/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DoctorDTO } from './doctorDTO';

export interface DoctorScheduleDTO {
    dayOfWeek?: number;
    doctor?: DoctorDTO;
    doctorId?: number;
    endTime?: string;
    scheduleId?: number;
    startTime?: string;
}
