/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DoctorScheduleDTO } from './doctorScheduleDTO';

export interface DoctorScheduleDTOPaginated {
    /** @nullable */
    data?: DoctorScheduleDTO[] | null;
    totalItems?: number;
}
