/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DoctorDTO } from './doctorDTO';

export interface DoctorDTOPaginated {
    /** @nullable */
    data?: DoctorDTO[] | null;
    totalItems?: number;
}
