/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface DoctorRegistration {
    /** @nullable */
    departmentId?: number | null;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    imageUrl?: string | null;
    /** @nullable */
    name?: string | null;
    /** @nullable */
    password?: string | null;
    /** @nullable */
    phoneNumber?: string | null;
    /** @nullable */
    specialization?: string | null;
}
