/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Patient } from './patient';

export interface EmergencyContact {
    contactId?: number;
    /**
     * @minLength 0
     * @maxLength 100
     * @nullable
     */
    email?: string | null;
    /**
     * @minLength 0
     * @maxLength 100
     * @nullable
     */
    name?: string | null;
    patient?: Patient;
    patientId?: number;
    /**
     * @minLength 0
     * @maxLength 15
     * @nullable
     */
    phoneNumber?: string | null;
    /**
     * @minLength 0
     * @maxLength 50
     * @nullable
     */
    relationship?: string | null;
}
