/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export type GetDiagnosesParams = {
    'AppointmentId.Equal'?: number;
    'AppointmentId.NotEquals'?: number;
    'AppointmentId.GreaterThan'?: number;
    'AppointmentId.GreaterThanOrEqual'?: number;
    'AppointmentId.LessThan'?: number;
    'AppointmentId.LessThanOrEqual'?: number;
    'AppointmentId.In'?: number[];
    'AppointmentId.IsNull'?: boolean;
    'AppointmentId.IsNotNull'?: boolean;
    'DiagnosisDate.Equal'?: string;
    'DiagnosisDate.NotEquals'?: string;
    'DiagnosisDate.GreaterThan'?: string;
    'DiagnosisDate.GreaterThanOrEqual'?: string;
    'DiagnosisDate.LessThan'?: string;
    'DiagnosisDate.LessThanOrEqual'?: string;
    'DiagnosisDate.IsNull'?: boolean;
    'DiagnosisDate.IsNotNull'?: boolean;
    'PatientId.Equal'?: number;
    'PatientId.NotEquals'?: number;
    'PatientId.GreaterThan'?: number;
    'PatientId.GreaterThanOrEqual'?: number;
    'PatientId.LessThan'?: number;
    'PatientId.LessThanOrEqual'?: number;
    'PatientId.In'?: number[];
    'PatientId.IsNull'?: boolean;
    'PatientId.IsNotNull'?: boolean;
    'DoctorId.Equal'?: number;
    'DoctorId.NotEquals'?: number;
    'DoctorId.GreaterThan'?: number;
    'DoctorId.GreaterThanOrEqual'?: number;
    'DoctorId.LessThan'?: number;
    'DoctorId.LessThanOrEqual'?: number;
    'DoctorId.In'?: number[];
    'DoctorId.IsNull'?: boolean;
    'DoctorId.IsNotNull'?: boolean;
    Search?: string;
    Page?: number;
    PageSize?: number;
    Skip?: number;
    Take?: number;
    SortBy?: string;
    SortOrder?: string;
};
