/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export type GetDoctorsParams = {
    'Name.Contains'?: string;
    'Name.NotContains'?: string;
    'Name.Equal'?: string;
    'Name.NotEquals'?: string;
    'Name.StartsWith'?: string;
    'Name.EndsWith'?: string;
    'Name.IsNull'?: boolean;
    'Name.IsNotNull'?: boolean;
    'Name.In'?: string[];
    'Specialization.Contains'?: string;
    'Specialization.NotContains'?: string;
    'Specialization.Equal'?: string;
    'Specialization.NotEquals'?: string;
    'Specialization.StartsWith'?: string;
    'Specialization.EndsWith'?: string;
    'Specialization.IsNull'?: boolean;
    'Specialization.IsNotNull'?: boolean;
    'Specialization.In'?: string[];
    'PhoneNumber.Contains'?: string;
    'PhoneNumber.NotContains'?: string;
    'PhoneNumber.Equal'?: string;
    'PhoneNumber.NotEquals'?: string;
    'PhoneNumber.StartsWith'?: string;
    'PhoneNumber.EndsWith'?: string;
    'PhoneNumber.IsNull'?: boolean;
    'PhoneNumber.IsNotNull'?: boolean;
    'PhoneNumber.In'?: string[];
    'Email.Contains'?: string;
    'Email.NotContains'?: string;
    'Email.Equal'?: string;
    'Email.NotEquals'?: string;
    'Email.StartsWith'?: string;
    'Email.EndsWith'?: string;
    'Email.IsNull'?: boolean;
    'Email.IsNotNull'?: boolean;
    'Email.In'?: string[];
    'DepartmentId.Equal'?: number;
    'DepartmentId.NotEquals'?: number;
    'DepartmentId.GreaterThan'?: number;
    'DepartmentId.GreaterThanOrEqual'?: number;
    'DepartmentId.LessThan'?: number;
    'DepartmentId.LessThanOrEqual'?: number;
    'DepartmentId.In'?: number[];
    'DepartmentId.IsNull'?: boolean;
    'DepartmentId.IsNotNull'?: boolean;
    Search?: string;
    Page?: number;
    PageSize?: number;
    Skip?: number;
    Take?: number;
    SortBy?: string;
    SortOrder?: string;
};
