/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export type GetInvoicesParams = {
    'InvoiceId.Equal'?: number;
    'InvoiceId.NotEquals'?: number;
    'InvoiceId.GreaterThan'?: number;
    'InvoiceId.GreaterThanOrEqual'?: number;
    'InvoiceId.LessThan'?: number;
    'InvoiceId.LessThanOrEqual'?: number;
    'InvoiceId.In'?: number[];
    'InvoiceId.IsNull'?: boolean;
    'InvoiceId.IsNotNull'?: boolean;
    'PatientId.Equal'?: number;
    'PatientId.NotEquals'?: number;
    'PatientId.GreaterThan'?: number;
    'PatientId.GreaterThanOrEqual'?: number;
    'PatientId.LessThan'?: number;
    'PatientId.LessThanOrEqual'?: number;
    'PatientId.In'?: number[];
    'PatientId.IsNull'?: boolean;
    'PatientId.IsNotNull'?: boolean;
    'AppointmentId.Equal'?: number;
    'AppointmentId.NotEquals'?: number;
    'AppointmentId.GreaterThan'?: number;
    'AppointmentId.GreaterThanOrEqual'?: number;
    'AppointmentId.LessThan'?: number;
    'AppointmentId.LessThanOrEqual'?: number;
    'AppointmentId.In'?: number[];
    'AppointmentId.IsNull'?: boolean;
    'AppointmentId.IsNotNull'?: boolean;
    'InvoiceDate.Equal'?: string;
    'InvoiceDate.NotEquals'?: string;
    'InvoiceDate.GreaterThan'?: string;
    'InvoiceDate.GreaterThanOrEqual'?: string;
    'InvoiceDate.LessThan'?: string;
    'InvoiceDate.LessThanOrEqual'?: string;
    'InvoiceDate.IsNull'?: boolean;
    'InvoiceDate.IsNotNull'?: boolean;
    'TotalAmount.Equal'?: number;
    'TotalAmount.NotEquals'?: number;
    'TotalAmount.GreaterThan'?: number;
    'TotalAmount.GreaterThanOrEqual'?: number;
    'TotalAmount.LessThan'?: number;
    'TotalAmount.LessThanOrEqual'?: number;
    'TotalAmount.In'?: number[];
    'TotalAmount.IsNull'?: boolean;
    'TotalAmount.IsNotNull'?: boolean;
    'Status.Contains'?: string;
    'Status.NotContains'?: string;
    'Status.Equal'?: string;
    'Status.NotEquals'?: string;
    'Status.StartsWith'?: string;
    'Status.EndsWith'?: string;
    'Status.IsNull'?: boolean;
    'Status.IsNotNull'?: boolean;
    'Status.In'?: string[];
    Page?: number;
    PageSize?: number;
    Skip?: number;
    Take?: number;
    SortBy?: string;
    SortOrder?: string;
    Search?: string;
};
