/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export type IdentityType = (typeof IdentityType)[keyof typeof IdentityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentityType = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
} as const;
