/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface IdentityUser {
    accessFailedCount?: number;
    /** @nullable */
    concurrencyStamp?: string | null;
    /** @nullable */
    email?: string | null;
    emailConfirmed?: boolean;
    /** @nullable */
    id?: string | null;
    lockoutEnabled?: boolean;
    /** @nullable */
    lockoutEnd?: string | null;
    /** @nullable */
    normalizedEmail?: string | null;
    /** @nullable */
    normalizedUserName?: string | null;
    /** @nullable */
    passwordHash?: string | null;
    /** @nullable */
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    /** @nullable */
    securityStamp?: string | null;
    twoFactorEnabled?: boolean;
    /** @nullable */
    userName?: string | null;
}
