/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export * from './appointment';
export * from './appointmentDTO';
export * from './appointmentDTOPaginated';
export * from './assignDoctorParams';
export * from './closeTicketParams';
export * from './department';
export * from './departmentDTO';
export * from './departmentDTOPaginated';
export * from './diagnosis';
export * from './diagnosisDTO';
export * from './diagnosisDTOPaginated';
export * from './doctor';
export * from './doctorDTO';
export * from './doctorDTOPaginated';
export * from './doctorRegistration';
export * from './doctorSchedule';
export * from './doctorScheduleCreateDTO';
export * from './doctorScheduleDTO';
export * from './doctorScheduleDTOPaginated';
export * from './downloadFileParams';
export * from './emergencyContact';
export * from './getAllDoctorSchedulesParams';
export * from './getAppointmentsParams';
export * from './getDepartmentsParams';
export * from './getDiagnosesParams';
export * from './getDoctorTicketsParams';
export * from './getDoctorsParams';
export * from './getFreeDoctorsParams';
export * from './getInvoicesParams';
export * from './getMessagesParams';
export * from './getPatientAppointmentsParams';
export * from './getPatientTicketsParams';
export * from './getPatientsParams';
export * from './getUnAssignedTicketsParams';
export * from './identityExistsParams';
export * from './identityType';
export * from './identityUser';
export * from './invoice';
export * from './invoiceDTO';
export * from './invoiceDTOPaginated';
export * from './loginModel';
export * from './loginResponse';
export * from './makeAppointmentRequest';
export * from './message';
export * from './messageDTO';
export * from './messageDTOPaginated';
export * from './openTicketParams';
export * from './patient';
export * from './patientDTO';
export * from './patientDTOPaginated';
export * from './patientRegistration';
export * from './sendMessageParams';
export * from './statusRequest';
export * from './ticket';
export * from './ticketDTO';
export * from './ticketPaginated';
export * from './tokenDTO';
export * from './uploadFileBody';
export * from './userProfileDTO';
export * from './weatherForecast';
