/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export * from './appointment';
export * from './appointmentDTO';
export * from './appointmentDTOPaginated';
export * from './department';
export * from './departmentDTO';
export * from './departmentDTOPaginated';
export * from './diagnosis';
export * from './diagnosisDTO';
export * from './diagnosisDTOPaginated';
export * from './doctor';
export * from './doctorDTO';
export * from './doctorDTOPaginated';
export * from './doctorRegistration';
export * from './doctorSchedule';
export * from './doctorScheduleDTO';
export * from './doctorScheduleDTOPaginated';
export * from './emergencyContact';
export * from './getAllDoctorSchedulesParams';
export * from './getAppointmentsParams';
export * from './getDepartmentsParams';
export * from './getDiagnosesParams';
export * from './getDoctorsParams';
export * from './getInvoicesParams';
export * from './getPatientsParams';
export * from './identityExistsParams';
export * from './identityType';
export * from './identityUser';
export * from './invoice';
export * from './invoicePaginated';
export * from './loginModel';
export * from './loginResponse';
export * from './patient';
export * from './patientDTO';
export * from './patientDTOPaginated';
export * from './patientRegistration';
export * from './tokenDTO';
export * from './uploadFileBody';
export * from './userProfileDTO';
export * from './weatherForecast';
