/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export * from './appointment';
export * from './department';
export * from './departmentDTO';
export * from './departmentDTOPaginated';
export * from './diagnosis';
export * from './doctor';
export * from './doctorDTO';
export * from './doctorDTOPaginated';
export * from './doctorRegistration';
export * from './doctorSchedule';
export * from './emergencyContact';
export * from './getDepartmentsParams';
export * from './getDoctorsParams';
export * from './identityUser';
export * from './invoice';
export * from './loginModel';
export * from './patient';
export * from './patientRegistration';
export * from './weatherForecast';
