/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Invoice } from './invoice';

export interface InvoicePaginated {
    /** @nullable */
    data?: Invoice[] | null;
    totalItems?: number;
}
