/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { PatientDTO } from './patientDTO';

export interface InvoiceDTO {
    /** @nullable */
    appointmentId?: number | null;
    invoiceDate?: string;
    invoiceId?: number;
    patient?: PatientDTO;
    patientId?: number;
    /** @nullable */
    status?: string | null;
    totalAmount?: number;
}
