/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Book API
 * OpenAPI spec version: v1
 */
import type { Patient } from './patient';

export interface Invoice {
    /** @nullable */
    appointmentId?: number | null;
    invoiceDate?: string;
    invoiceId?: number;
    patient?: Patient;
    patientId?: number;
    /**
     * @minLength 0
     * @maxLength 50
     * @nullable
     */
    status?: string | null;
    totalAmount?: number;
}
