/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Book API
 * OpenAPI spec version: v1
 */

export interface LoginModel {
    /** @minLength 1 */
    email: string;
    /** @minLength 1 */
    password: string;
}
