/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { TokenDTO } from './tokenDTO';
import type { UserProfileDTO } from './userProfileDTO';

export interface LoginResponse {
    token?: TokenDTO;
    user?: UserProfileDTO;
}
