/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface MakeAppointmentRequest {
    appointmentDate?: string;
    appointmentId?: number;
    doctorId?: number;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    name?: string | null;
    /** @nullable */
    patientId?: number | null;
    /** @nullable */
    phoneNumber?: string | null;
}
