/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { MessageDTO } from './messageDTO';

export interface MessageDTOPaginated {
    /** @nullable */
    data?: MessageDTO[] | null;
    nextPage?: number;
    totalItems?: number;
}
