/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface PatientRegistration {
    dateOfBirth?: string;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    gender?: string | null;
    /** @nullable */
    healthInsurance?: string | null;
    /** @nullable */
    name?: string | null;
    /** @nullable */
    password?: string | null;
    /** @nullable */
    phoneNumber?: string | null;
}
