/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { PatientDTO } from './patientDTO';

export interface PatientDTOPaginated {
    /** @nullable */
    data?: PatientDTO[] | null;
    totalItems?: number;
}
