/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { PatientDTO } from './patientDTO';

export interface PatientDTOPaginated {
    /** @nullable */
    data?: PatientDTO[] | null;
    nextPage?: number;
    totalItems?: number;
}
