/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export type SendMessageParams = {
    ticketId?: string;
    content?: string;
    userId?: string;
};
