/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { Ticket } from './ticket';

export interface TicketPaginated {
    /** @nullable */
    data?: Ticket[] | null;
    nextPage?: number;
    totalItems?: number;
}
