/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */
import type { DoctorDTO } from './doctorDTO';
import type { PatientDTO } from './patientDTO';

export interface UserProfileDTO {
    /** @nullable */
    address?: string | null;
    doctor?: DoctorDTO;
    /** @nullable */
    email?: string | null;
    /** @nullable */
    id?: string | null;
    patient?: PatientDTO;
    /** @nullable */
    phoneNumber?: string | null;
    /** @nullable */
    roles?: string[] | null;
    /** @nullable */
    userName?: string | null;
}
