/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface WeatherForecast {
    date?: string;
    /** @nullable */
    summary?: string | null;
    temperatureC?: number;
    readonly temperatureF?: number;
}
