/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Hopital Management System Api
 * OpenAPI spec version: v1
 */

export interface WeeklyRevenueDTO {
    amount?: number;
    /** @nullable */
    dayOfWeek?: string | null;
}
